### PR TITLE
Updates for metacontrol integration

### PR DESCRIPTION
**Pull request by jginesclavero**
Hi @marioney 
I have updated and fixed some wrapper issues and, as we talked yesterday, we are using the system modes pkg to do the nav2 reconfiguration. 
This PR includes QoS msgs changes requested in our meeting

### CODE REVIEW

**Comment by marioney** [comment]
I think we should merge this with https://github.com/tud-cor/mc_mros_reasoner/tree/foxy_add_action_server first, so we can take all the changes there, then we can merge everything into foxy_devel

@jginesclavero is that Ok with you?

**Comment by jginesclavero** [comment]
Yes, of course!

**Comment by marioney** [comment]
So, after a rebase, I've solved some conflicts that appear.  
@jginesclavero  Can you double check that everything is OK now?

**Review by marioney — APPROVED** [review]

**Comment by jginesclavero** [comment]
LGTM!

**Pull request merged**
