### PR TITLE
Re-factor rosmodel2owl

### PR DESCRIPTION
**Pull request by ipa-nhg**
I tried to clean the rosmodel2owl script and I created a yaml file to get all the needed information: https://github.com/ipa-nhg/mc_mros_reasoner/blob/629d799e93b57295da55466e0925eeba8b445612/mros1_reasoner/config/nav_config.yaml

The path to this configuration file should be given as argument (temporally https://github.com/tud-cor/mc_mros_reasoner/compare/master...ipa-nhg:RefactorRosModel2OWL?expand=1#diff-891c2c9fb27b3772e711546a0d747a40a3758a886bcea069ff49b38e8b23a217R33)

The ROS model part is tested and works, but I couldn't complete the code (lines 75-83) because I miss one file of the domain model ontology (ros_navigation.owl).

### CODE REVIEW

**Comment by ipa-nhg** [comment]
ping @chcorbato

**Comment by chcorbato** [comment]
> The ROS model part is tested and works, but I couldn't complete the code (lines 75-83) because I miss one file of the domain model ontology (ros_navigation.owl).

Sorry I failed at coming back to this on Friday.

I have created that file (should be in the owl directory that should contain all ontology files) and modified [nav_config.yaml ](https://github.com/tud-cor/mc_mros_reasoner/blob/rosnavigationowl/mros1_reasoner/config/nav_config.yaml)accordingly.
See 09f78cdf6365fd609c239f924d8297eca784d1ff in branch [rosnavigationowl](rosnavigationowl)
Can you check if it works?

**Comment by ipa-nhg** [comment]
@chcorbato thanks for your help. I think the rosnavigation.owl file is still not complete, I get the following error:

`The domain ontology provided does not contain a Function  f_navigate`
 given by: https://github.com/tud-cor/mc_mros_reasoner/blob/b43e8dea25bf628acdfae27c07edbd60a0003634/mros1_reasoner/scripts/rosmodel2owl.py#L50-L54 

I think the script works now, I also updated it to get the configuration file as argument, this means for the navigation example:

`rosrun mros1_reasoner rosmodel2owl.py  ../config/nav_config.yaml`

Lastly for the navigation experiments I showed that there was still some information taken by the [csv file](https://github.com/tud-cor/mc_mros_reasoner/blob/b43e8dea25bf628acdfae27c07edbd60a0003634/mros1_reasoner/expected_qas.csv) and not present for the [system model](https://github.com/rosin-project/metacontrol_move_base_configurations/blob/master/f1_v1_r1/f1_v1_r1.rossystem), the performance.  -> Issue open https://github.com/rosin-project/metacontrol_move_base_configurations/issues/8

**Review by chcorbato — APPROVED** [review]
LGTM!

**Comment by ipa-nhg** [comment]
@chcorbato did you try the script with a valid navigation.owl file (i.e., that contains the function f_navigate)? or with a modification of the configuration file to point other function that is provided by the owl file ( [line 7](https://github.com/ipa-nhg/mc_mros_reasoner/blob/RefactorRosModel2OWL/mros1_reasoner/config/nav_config.yaml#L7)  )? Is it working?

**Review by chcorbato — APPROVED** [review]
I have committed the fix for the f_navigate problem 4d6ecc3cbe804ab0a67802dab18e67d39fb33c3d
I have then tested the script and it creates am owl file that seems correct 🎉

**Pull request merged**
